// <auto-generated />
using System;
using KhachSan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhachSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250402220608_FixPhongLoaiPhongRelationship")]
    partial class FixPhongLoaiPhongRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhachSan.Data.CaLamViec", b =>
                {
                    b.Property<int>("MaCaLamViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCaLamViec"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienCaTiepTheo")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TongTienChuyenGiao")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TongTienTrongCa")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang làm việc");

                    b.HasKey("MaCaLamViec")
                        .HasName("PK__CaLamVie__E545F62591AA82E2");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaNhanVienCaTiepTheo");

                    b.ToTable("CaLamViec", null, t =>
                        {
                            t.HasTrigger("TR_KiemTraNhanVien_CaLamViec");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KhachSan.Data.ChiTietDichVu", b =>
                {
                    b.Property<int>("MaChiTietDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDichVu"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MaChiTietDichVu")
                        .HasName("PK__ChiTietD__11EFCA675B5F763E");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaDichVu");

                    b.ToTable("ChiTietDichVu", null, t =>
                        {
                            t.HasTrigger("TR_CapNhat_TongTienDichVu");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KhachSan.Data.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDatPhong"));

                    b.Property<int?>("MaGiamGia")
                        .HasColumnType("int");

                    b.Property<int?>("MaKhachHangLuuTru")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhomDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTraPhong")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("TongThoiGian")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTienDichVu")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TongTienTheoThoiGian")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chờ xác nhận");

                    b.Property<string>("TrangThaiBaoCaoTamTru")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chưa báo cáo");

                    b.Property<string>("TrangThaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chưa thanh toán");

                    b.HasKey("MaDatPhong")
                        .HasName("PK__DatPhong__6344ADEAC3325991");

                    b.HasIndex("MaGiamGia");

                    b.HasIndex("MaKhachHangLuuTru");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaNhomDatPhong");

                    b.HasIndex("MaPhong");

                    b.ToTable("DatPhong", null, t =>
                        {
                            t.HasTrigger("UpdateNgayCapNhat_DatPhong");

                            t.HasTrigger("UpdatePhong_DangSuDung");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KhachSan.Data.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("MaDichVu")
                        .HasName("PK__DichVu__C0E6DE8FA534368E");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("KhachSan.Data.GiamGium", b =>
                {
                    b.Property<int>("MaGiamGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiamGiaId"));

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuongDaDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SoLuongMa")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienDatToiThieu")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TenMaGiamGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("MaGiamGiaId")
                        .HasName("PK__GiamGia__C28471F37E29E6EE");

                    b.HasIndex(new[] { "MaGiamGia" }, "UQ__GiamGia__EF9458E539872A42")
                        .IsUnique();

                    b.ToTable("GiamGia");
                });

            modelBuilder.Entity("KhachSan.Data.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHoaDon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaCaLamViec")
                        .HasColumnType("int");

                    b.Property<int?>("MaDatPhong")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhomDatPhong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chưa thanh toán");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13B9D48AA98");

                    b.HasIndex("MaCaLamViec");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaNhomDatPhong");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("KhachSan.Data.KhachHangLuuTru", b =>
                {
                    b.Property<int>("MaKhachHangLuuTru")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHangLuuTru"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiGiayTo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayCapGiayTo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiCapGiayTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoGiayTo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhachHangLuuTru")
                        .HasName("PK__KhachHan__7FE4FD2A61CC29E5");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex(new[] { "SoGiayTo" }, "UQ__KhachHan__04338D259D39AD6F")
                        .IsUnique()
                        .HasFilter("[SoGiayTo] IS NOT NULL");

                    b.ToTable("KhachHangLuuTru", null, t =>
                        {
                            t.HasTrigger("UpdateNgayCapNhat_KhachHangLuuTru");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KhachSan.Data.LichSuThaoTac", b =>
                {
                    b.Property<int>("MaThaoTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThaoTac"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThaoTac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaCaLamViec")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaThaoTac")
                        .HasName("PK__LichSuTh__32ACE29307E9F52E");

                    b.HasIndex("MaCaLamViec");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("LichSuThaoTac", (string)null);
                });

            modelBuilder.Entity("KhachSan.Data.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiPhong"));

                    b.Property<decimal>("GiaTheoGio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("GiaTheoNgay")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("MaLoaiPhong")
                        .HasName("PK__LoaiPhon__230212172062E897");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("KhachSan.Data.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaPin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaPIN");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Hoạt động");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D7625B6808D1");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__55F68FC03B6F6DD7")
                        .IsUnique();

                    b.ToTable("NguoiDung", null, t =>
                        {
                            t.HasTrigger("UpdateNgayCapNhat_NguoiDung");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("KhachSan.Data.NhomDatPhong", b =>
                {
                    b.Property<int>("MaNhomDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhomDatPhong"));

                    b.Property<string>("HoTenNguoiDaiDien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNguoiDaiDien")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoaiNguoiDaiDien")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang xử lý");

                    b.HasKey("MaNhomDatPhong")
                        .HasName("PK__NhomDatP__F91B37A1EAF9428A");

                    b.HasIndex("MaNguoiDaiDien");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("NhomDatPhong", (string)null);
                });

            modelBuilder.Entity("KhachSan.Data.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<bool>("DangSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LoaiPhongMaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("ThoiGianTraPhongCuoi")
                        .HasColumnType("datetime");

                    b.HasKey("MaPhong")
                        .HasName("PK__Phong__20BD5E5BEB5F3F4F");

                    b.HasIndex("LoaiPhongMaLoaiPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.HasIndex(new[] { "SoPhong" }, "UQ__Phong__7C736CA1FB3838F8")
                        .IsUnique();

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("KhachSan.Data.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaNguoiGui")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiNhan")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chưa đọc");

                    b.HasKey("MaThongBao")
                        .HasName("PK__ThongBao__04DEB54E13533773");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaNguoiNhan");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("KhachSan.Data.CaLamViec", b =>
                {
                    b.HasOne("KhachSan.Data.NguoiDung", "MaNhanVienNavigation")
                        .WithMany("CaLamViecMaNhanVienNavigations")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__CaLamViec__MaNha__628FA481");

                    b.HasOne("KhachSan.Data.NguoiDung", "MaNhanVienCaTiepTheoNavigation")
                        .WithMany("CaLamViecMaNhanVienCaTiepTheoNavigations")
                        .HasForeignKey("MaNhanVienCaTiepTheo")
                        .HasConstraintName("FK__CaLamViec__MaNha__6383C8BA");

                    b.Navigation("MaNhanVienCaTiepTheoNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("KhachSan.Data.ChiTietDichVu", b =>
                {
                    b.HasOne("KhachSan.Data.DatPhong", "MaDatPhongNavigation")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDatPhong")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDi__MaDat__76969D2E");

                    b.HasOne("KhachSan.Data.DichVu", "MaDichVuNavigation")
                        .WithMany("ChiTietDichVus")
                        .HasForeignKey("MaDichVu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDi__MaDic__778AC167");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaDichVuNavigation");
                });

            modelBuilder.Entity("KhachSan.Data.DatPhong", b =>
                {
                    b.HasOne("KhachSan.Data.GiamGium", "MaGiamGiaNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaGiamGia")
                        .HasConstraintName("FK__DatPhong__MaGiam__72C60C4A");

                    b.HasOne("KhachSan.Data.KhachHangLuuTru", "MaKhachHangLuuTruNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKhachHangLuuTru")
                        .HasConstraintName("FK__DatPhong__MaKhac__71D1E811");

                    b.HasOne("KhachSan.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DatPhongMaNguoiDungNavigations")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__DatPhong__MaNguo__6EF57B66");

                    b.HasOne("KhachSan.Data.NguoiDung", "MaNhanVienNavigation")
                        .WithMany("DatPhongMaNhanVienNavigations")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__DatPhong__MaNhan__6FE99F9F");

                    b.HasOne("KhachSan.Data.NhomDatPhong", "MaNhomDatPhongNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaNhomDatPhong")
                        .HasConstraintName("FK__DatPhong__MaNhom__6E01572D");

                    b.HasOne("KhachSan.Data.Phong", "MaPhongNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK__DatPhong__MaPhon__70DDC3D8");

                    b.Navigation("MaGiamGiaNavigation");

                    b.Navigation("MaKhachHangLuuTruNavigation");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaNhomDatPhongNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("KhachSan.Data.HoaDon", b =>
                {
                    b.HasOne("KhachSan.Data.CaLamViec", "MaCaLamViecNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaCaLamViec")
                        .HasConstraintName("FK__HoaDon__MaCaLamV__7F2BE32F");

                    b.HasOne("KhachSan.Data.DatPhong", "MaDatPhongNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaDatPhong")
                        .HasConstraintName("FK__HoaDon__MaDatPho__01142BA1");

                    b.HasOne("KhachSan.Data.NhomDatPhong", "MaNhomDatPhongNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNhomDatPhong")
                        .HasConstraintName("FK__HoaDon__MaNhomDa__00200768");

                    b.Navigation("MaCaLamViecNavigation");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaNhomDatPhongNavigation");
                });

            modelBuilder.Entity("KhachSan.Data.KhachHangLuuTru", b =>
                {
                    b.HasOne("KhachSan.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("KhachHangLuuTrus")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__KhachHang__MaNgu__5441852A");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("KhachSan.Data.LichSuThaoTac", b =>
                {
                    b.HasOne("KhachSan.Data.CaLamViec", "MaCaLamViecNavigation")
                        .WithMany("LichSuThaoTacs")
                        .HasForeignKey("MaCaLamViec")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuTha__MaCaL__05D8E0BE");

                    b.HasOne("KhachSan.Data.NguoiDung", "MaNhanVienNavigation")
                        .WithMany("LichSuThaoTacs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuTha__MaNha__06CD04F7");

                    b.Navigation("MaCaLamViecNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("KhachSan.Data.NhomDatPhong", b =>
                {
                    b.HasOne("KhachSan.Data.NguoiDung", "MaNguoiDaiDienNavigation")
                        .WithMany("NhomDatPhongMaNguoiDaiDienNavigations")
                        .HasForeignKey("MaNguoiDaiDien")
                        .HasConstraintName("FK__NhomDatPh__MaNgu__4BAC3F29");

                    b.HasOne("KhachSan.Data.NguoiDung", "MaNhanVienNavigation")
                        .WithMany("NhomDatPhongMaNhanVienNavigations")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__NhomDatPh__MaNha__4CA06362");

                    b.Navigation("MaNguoiDaiDienNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("KhachSan.Data.Phong", b =>
                {
                    b.HasOne("KhachSan.Data.LoaiPhong", null)
                        .WithMany("Phongs")
                        .HasForeignKey("LoaiPhongMaLoaiPhong");

                    b.HasOne("KhachSan.Data.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong")
                        .IsRequired()
                        .HasConstraintName("FK__Phong__MaLoaiPho__45F365D3");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("KhachSan.Data.ThongBao", b =>
                {
                    b.HasOne("KhachSan.Data.NguoiDung", "MaNguoiGuiNavigation")
                        .WithMany("ThongBaoMaNguoiGuiNavigations")
                        .HasForeignKey("MaNguoiGui")
                        .HasConstraintName("FK__ThongBao__MaNguo__0D7A0286");

                    b.HasOne("KhachSan.Data.NguoiDung", "MaNguoiNhanNavigation")
                        .WithMany("ThongBaoMaNguoiNhanNavigations")
                        .HasForeignKey("MaNguoiNhan")
                        .IsRequired()
                        .HasConstraintName("FK__ThongBao__MaNguo__0E6E26BF");

                    b.Navigation("MaNguoiGuiNavigation");

                    b.Navigation("MaNguoiNhanNavigation");
                });

            modelBuilder.Entity("KhachSan.Data.CaLamViec", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("LichSuThaoTacs");
                });

            modelBuilder.Entity("KhachSan.Data.DatPhong", b =>
                {
                    b.Navigation("ChiTietDichVus");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("KhachSan.Data.DichVu", b =>
                {
                    b.Navigation("ChiTietDichVus");
                });

            modelBuilder.Entity("KhachSan.Data.GiamGium", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("KhachSan.Data.KhachHangLuuTru", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("KhachSan.Data.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("KhachSan.Data.NguoiDung", b =>
                {
                    b.Navigation("CaLamViecMaNhanVienCaTiepTheoNavigations");

                    b.Navigation("CaLamViecMaNhanVienNavigations");

                    b.Navigation("DatPhongMaNguoiDungNavigations");

                    b.Navigation("DatPhongMaNhanVienNavigations");

                    b.Navigation("KhachHangLuuTrus");

                    b.Navigation("LichSuThaoTacs");

                    b.Navigation("NhomDatPhongMaNguoiDaiDienNavigations");

                    b.Navigation("NhomDatPhongMaNhanVienNavigations");

                    b.Navigation("ThongBaoMaNguoiGuiNavigations");

                    b.Navigation("ThongBaoMaNguoiNhanNavigations");
                });

            modelBuilder.Entity("KhachSan.Data.NhomDatPhong", b =>
                {
                    b.Navigation("DatPhongs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("KhachSan.Data.Phong", b =>
                {
                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
